import socket
import sys

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.settimeout(5)
host = sys.argv[1] if len(sys.argv) > 1 else 'localhost'
port = int(sys.argv[2]) if len(sys.argv) > 2 else 2500
s.connect((host, port))
banner = s.recv(4096)
print('Banner:', banner)
s.send(b'EHLO test\r\n')
print('> EHLO test')
resp = s.recv(4096)
print('Resp:', resp)
s.send(b'MAIL FROM:<test@test.com>\r\n')
print('> MAIL FROM')
resp = s.recv(4096)
print('Resp:', resp)
s.send(b'RCPT TO:<root@localhost>\r\n')
print('> RCPT TO')
resp = s.recv(4096)
print('Resp:', resp)
s.send(b'DATA\r\n')
print('> DATA')
resp = s.recv(4096)
print('Resp:', resp)
s.send(b'From: test@test.com\r\nSubject: test\r\n\r\nTest body\r\n.\r\n')
print('> data')
resp = s.recv(4096)
print('Resp:', resp)
s.send(b'QUIT\r\n')
print('> QUIT')
resp = s.recv(4096)
print('Resp:', resp)
s.close()
